export const boards = [
  [
    [
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: true },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "aqua", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: true },
      { color: "green", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "aqua", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "red", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "red", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "grey", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "grey", blocked: false },
      { color: "pink", blocked: false },
      { color: "yellow", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "grey", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "yellow", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "yellow", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "yellow", blocked: false },
      { color: "yellow", blocked: false },
      { color: "yellow", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
    ],
  ],
  [
    [
      { color: "pink", blocked: false },
      { color: "pink", blocked: true },
      { color: "pink", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: true },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "purple", blocked: false },
      { color: "yellow", blocked: false },
      { color: "yellow", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "purple", blocked: false },
      { color: "yellow", blocked: false },
      { color: "yellow", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "red", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "aqua", blocked: false },
    ],
  ],
  [
    [
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "blue", blocked: false },
      { color: "purple", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "orange", blocked: false },
      { color: "green", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
      { color: "orange", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "blue", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
      { color: "pink", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "aqua", blocked: false },
      { color: "purple", blocked: false },
      { color: "aqua", blocked: false },
      { color: "red", blocked: false },
      { color: "grey", blocked: false },
      { color: "red", blocked: false },
      { color: "pink", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "purple", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "aqua", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "red", blocked: false },
      { color: "purple", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
    ],
  ],
  [
    [
      { color: "purple", blocked: false },
      { color: "orange", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
      { color: "green", blocked: false },
    ],
    [
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
    ],
    [
      { color: "blue", blocked: false },
      { color: "orange", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "green", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
    ],
    [
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
    ],
    [
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "green", blocked: false },
    ],
    [
      { color: "aqua", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
  ],
  [
    [
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "purple", blocked: false },
      { color: "orange", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "green", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "orange", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "green", blocked: false },
      { color: "orange", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "green", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "blue", blocked: false },
    ],
    [
      { color: "purple", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "pink", blocked: false },
      { color: "aqua", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "aqua", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "grey", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "red", blocked: false },
      { color: "red", blocked: false },
      { color: "lime", blocked: false },
      { color: "lime", blocked: false },
    ],
    [
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "pink", blocked: false },
      { color: "brown", blocked: false },
      { color: "brown", blocked: false },
      { color: "brown", blocked: false },
      { color: "lime", blocked: false },
      { color: "lime", blocked: false },
    ],
  ],
];
